################################################################################
### Package dependency management ##############################################
################################################################################
## Package for reading/writing Excel files
# Install latest version (0.6.5)
install.packages("xlsx")
library(xlsx)

## Take a snapshot to save changes
renv::snapshot()
## Check status
renv::status()
## Restore a package or project dependencies from lockfile
## as previously generated by snapshot()
renv::restore()

## Remove a package
remove.packages("xlsx")

## Check available versions
install.packages("versions")
library(versions)
# Use available.versions() of versions to check available versions
available.versions("xlsx")
# $xlsx
# version       date available
# 1    0.6.5 2020-11-10      TRUE
# 2  0.6.4.2 2020-09-12      TRUE
# 3    0.6.3 2020-02-28      TRUE
# 4    0.6.2 2020-02-12      TRUE
# 5    0.6.1 2018-06-11      TRUE
# 6    0.5.7 2014-08-02      TRUE
# 7    0.5.5 2013-12-10     FALSE

## Using devtools to install older package versions
install.packages("devtools")
library(devtools)
# Use install_version() of devtools to install version you need
install_version("xlsx", version = "0.6.3", repos = "http://cran.us.r-project.org")

## Check status
renv::status()

## Package for data visualisation 
# ggplot2 takes long to install!!!
install.packages("ggplot2")
library(ggplot2)

################################################################################